require 'opskeleton/version'
require 'thor'
require 'thor/group'
require 'yaml'
require 'ostruct'
require 'opskeleton/thorable'
require 'opskeleton/dockerize'
require 'opskeleton/package'
require 'opskeleton/clean'
require 'opskeleton/bump'
require 'opskeleton/generate_puppet'
require 'opskeleton/generate_chef'
require 'opskeleton/deploy'
require 'opskeleton/module'

